name: Build and Deploy TypeDoc

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Documentation
        run: npx typedoc --githubPages true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v2
        with:
          name: typedoc-artifact
          path: "./docs"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Documentation Artifact
        uses: actions/download-artifact@v2
        with:
          name: typedoc-artifact
          path: "./docs"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
